#pragma once

using namespace ATL;

template <class T>
class CProxy_IPluginEvents : public IConnectionPointImpl<T, &__uuidof(_IPluginEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
